// Static seed data: 27 realistic Indian electronics products across six
// categories, using placehold.co for placeholder product imagery (no image
// upload pipeline needed for a college project).
const productImage = (label, bg) => `https://placehold.co/600x600/${bg}/ffffff?text=${encodeURIComponent(label)}`;

const products = [
  // ---------------- Mobiles ----------------
  {
    name: 'Samsung Galaxy S24 5G',
    brand: 'Samsung',
    category: 'Mobiles',
    price: 74999,
    mrp: 79999,
    description:
      'Flagship Samsung Galaxy S24 5G with a stunning Dynamic AMOLED display, powerful Exynos processor, and a versatile triple camera system built for everyday photography.',
    specifications: {
      Display: '6.2-inch Dynamic AMOLED 2X, 120Hz',
      Processor: 'Exynos 2400',
      RAM: '8GB',
      Storage: '256GB',
      Battery: '4000mAh with 25W fast charging',
      Camera: '50MP + 12MP + 10MP Triple Rear Camera',
    },
    stock: 25,
    rating: 4.6,
    num_reviews: 184,
    featured: true,
  },
  {
    name: 'Samsung Galaxy M14 5G',
    brand: 'Samsung',
    category: 'Mobiles',
    price: 13999,
    mrp: 16999,
    description:
      'Samsung Galaxy M14 5G offers a massive 6000mAh battery, 50MP camera, and 5G connectivity — a reliable everyday smartphone at a budget-friendly price.',
    specifications: {
      Display: '6.6-inch PLS LCD, 90Hz',
      Processor: 'Exynos 1330',
      RAM: '6GB',
      Storage: '128GB',
      Battery: '6000mAh with 25W fast charging',
      Camera: '50MP + 2MP + 2MP Triple Rear Camera',
    },
    stock: 40,
    rating: 4.2,
    num_reviews: 302,
    featured: false,
  },
  {
    name: 'OnePlus 12 5G',
    brand: 'OnePlus',
    category: 'Mobiles',
    price: 64999,
    mrp: 69999,
    description:
      'OnePlus 12 5G brings flagship-grade Snapdragon performance, a Hasselblad-tuned camera system, and blazing 100W SUPERVOOC charging.',
    specifications: {
      Display: '6.82-inch LTPO AMOLED, 120Hz',
      Processor: 'Snapdragon 8 Gen 3',
      RAM: '12GB',
      Storage: '256GB',
      Battery: '5400mAh with 100W SUPERVOOC charging',
      Camera: '50MP + 64MP + 48MP Triple Rear Camera',
    },
    stock: 18,
    rating: 4.7,
    num_reviews: 96,
    featured: true,
  },
  {
    name: 'OnePlus Nord CE 4',
    brand: 'OnePlus',
    category: 'Mobiles',
    price: 24999,
    mrp: 27999,
    description:
      'OnePlus Nord CE 4 combines a Snapdragon 7 Gen 3 chipset with a slim design and fast charging, ideal for smooth day-to-day performance.',
    specifications: {
      Display: '6.7-inch AMOLED, 120Hz',
      Processor: 'Snapdragon 7 Gen 3',
      RAM: '8GB',
      Storage: '128GB',
      Battery: '5500mAh with 100W SUPERVOOC charging',
      Camera: '50MP + 8MP Dual Rear Camera',
    },
    stock: 30,
    rating: 4.4,
    num_reviews: 128,
    featured: false,
  },
  {
    name: 'Xiaomi 14 Civi',
    brand: 'Xiaomi',
    category: 'Mobiles',
    price: 39999,
    mrp: 44999,
    description:
      'Xiaomi 14 Civi is a slim, camera-focused smartphone with a Leica-tuned lens setup and a sleek glass-and-metal design.',
    specifications: {
      Display: '6.55-inch AMOLED, 120Hz',
      Processor: 'Snapdragon 8s Gen 3',
      RAM: '8GB',
      Storage: '256GB',
      Battery: '4700mAh with 67W fast charging',
      Camera: '50MP Leica Triple Rear Camera',
    },
    stock: 15,
    rating: 4.5,
    num_reviews: 54,
    featured: false,
  },
  {
    name: 'Redmi Note 13 Pro',
    brand: 'Xiaomi',
    category: 'Mobiles',
    price: 25999,
    mrp: 28999,
    description:
      'Redmi Note 13 Pro features a curved AMOLED display and a 200MP main camera, delivering flagship-like photography at a mid-range price.',
    specifications: {
      Display: '6.67-inch Curved AMOLED, 120Hz',
      Processor: 'Snapdragon 7s Gen 2',
      RAM: '8GB',
      Storage: '256GB',
      Battery: '5100mAh with 67W fast charging',
      Camera: '200MP + 8MP + 2MP Triple Rear Camera',
    },
    stock: 35,
    rating: 4.4,
    num_reviews: 210,
    featured: true,
  },

  // ---------------- Laptops ----------------
  {
    name: 'Lenovo IdeaPad Slim 3',
    brand: 'Lenovo',
    category: 'Laptops',
    price: 42990,
    mrp: 49990,
    description:
      'Lenovo IdeaPad Slim 3 is a lightweight everyday laptop with AMD Ryzen performance, ideal for study, browsing, and office work.',
    specifications: {
      Processor: 'AMD Ryzen 5 7520U',
      RAM: '16GB DDR5',
      Storage: '512GB SSD',
      Display: '15.6-inch FHD',
      Graphics: 'AMD Radeon Graphics',
      OS: 'Windows 11 Home',
    },
    stock: 20,
    rating: 4.3,
    num_reviews: 87,
    featured: true,
  },
  {
    name: 'Lenovo ThinkPad E14',
    brand: 'Lenovo',
    category: 'Laptops',
    price: 62990,
    mrp: 69990,
    description:
      'Lenovo ThinkPad E14 delivers business-grade durability and performance, with a spill-resistant keyboard and long battery life.',
    specifications: {
      Processor: 'Intel Core i5-1335U',
      RAM: '16GB DDR4',
      Storage: '512GB SSD',
      Display: '14-inch FHD IPS',
      Graphics: 'Intel Iris Xe',
      OS: 'Windows 11 Pro',
    },
    stock: 12,
    rating: 4.6,
    num_reviews: 45,
    featured: false,
  },
  {
    name: 'HP Pavilion 15',
    brand: 'HP',
    category: 'Laptops',
    price: 54990,
    mrp: 61990,
    description:
      'HP Pavilion 15 pairs a crisp micro-edge display with solid multitasking performance, wrapped in a sleek aluminum design.',
    specifications: {
      Processor: 'Intel Core i5-1335U',
      RAM: '16GB DDR4',
      Storage: '512GB SSD',
      Display: '15.6-inch FHD IPS',
      Graphics: 'Intel Iris Xe',
      OS: 'Windows 11 Home',
    },
    stock: 22,
    rating: 4.4,
    num_reviews: 132,
    featured: true,
  },
  {
    name: 'HP 15s Laptop',
    brand: 'HP',
    category: 'Laptops',
    price: 38990,
    mrp: 44990,
    description:
      'HP 15s is a compact, reliable laptop for students, with a full-HD display and dependable all-day battery life.',
    specifications: {
      Processor: 'Intel Core i3-1215U',
      RAM: '8GB DDR4',
      Storage: '512GB SSD',
      Display: '15.6-inch FHD',
      Graphics: 'Intel UHD Graphics',
      OS: 'Windows 11 Home',
    },
    stock: 28,
    rating: 4.1,
    num_reviews: 176,
    featured: false,
  },
  {
    name: 'Dell Inspiron 15 3520',
    brand: 'Dell',
    category: 'Laptops',
    price: 47990,
    mrp: 53990,
    description:
      'Dell Inspiron 15 3520 offers dependable performance for everyday computing with a comfortable keyboard and vivid display.',
    specifications: {
      Processor: 'Intel Core i5-1235U',
      RAM: '16GB DDR4',
      Storage: '512GB SSD',
      Display: '15.6-inch FHD',
      Graphics: 'Intel Iris Xe',
      OS: 'Windows 11 Home',
    },
    stock: 19,
    rating: 4.3,
    num_reviews: 98,
    featured: false,
  },
  {
    name: 'Dell XPS 13',
    brand: 'Dell',
    category: 'Laptops',
    price: 119990,
    mrp: 129990,
    description:
      'Dell XPS 13 is a premium ultraportable with an InfinityEdge display and CNC-machined aluminum chassis, built for professionals on the move.',
    specifications: {
      Processor: 'Intel Core i7-1355U',
      RAM: '16GB LPDDR5',
      Storage: '1TB SSD',
      Display: '13.4-inch FHD+ InfinityEdge',
      Graphics: 'Intel Iris Xe',
      OS: 'Windows 11 Pro',
    },
    stock: 8,
    rating: 4.8,
    num_reviews: 33,
    featured: true,
  },

  // ---------------- Audio ----------------
  {
    name: 'JBL Flip 6 Bluetooth Speaker',
    brand: 'JBL',
    category: 'Audio',
    price: 9999,
    mrp: 11999,
    description:
      'JBL Flip 6 delivers bold JBL Pro Sound in a rugged, IP67 waterproof design perfect for outdoor use.',
    specifications: {
      Type: 'Portable Bluetooth Speaker',
      'Battery Life': 'Up to 12 hours',
      Connectivity: 'Bluetooth 5.1',
      'Water Resistance': 'IP67',
    },
    stock: 34,
    rating: 4.6,
    num_reviews: 214,
    featured: true,
  },
  {
    name: 'JBL Tune 510BT Headphones',
    brand: 'JBL',
    category: 'Audio',
    price: 2499,
    mrp: 3999,
    description:
      'JBL Tune 510BT on-ear headphones deliver punchy JBL Pure Bass sound with up to 40 hours of battery life.',
    specifications: {
      Type: 'On-Ear Wireless Headphones',
      'Battery Life': 'Up to 40 hours',
      Connectivity: 'Bluetooth 5.0',
      'Driver Size': '32mm',
    },
    stock: 50,
    rating: 4.3,
    num_reviews: 340,
    featured: false,
  },
  {
    name: 'boAt Rockerz 450 Headphones',
    brand: 'boAt',
    category: 'Audio',
    price: 1399,
    mrp: 2990,
    description:
      'boAt Rockerz 450 wireless on-ear headphones offer punchy bass, a foldable design, and up to 15 hours of playback.',
    specifications: {
      Type: 'On-Ear Wireless Headphones',
      'Battery Life': 'Up to 15 hours',
      Connectivity: 'Bluetooth 5.0',
      'Driver Size': '40mm',
    },
    stock: 60,
    rating: 4.2,
    num_reviews: 512,
    featured: true,
  },
  {
    name: 'boAt Stone 1200 Speaker',
    brand: 'boAt',
    category: 'Audio',
    price: 1799,
    mrp: 3490,
    description:
      'boAt Stone 1200 portable speaker packs 14W RMS immersive sound with IPX7 water resistance for indoor and outdoor use.',
    specifications: {
      Type: 'Portable Bluetooth Speaker',
      'Battery Life': 'Up to 8 hours',
      Connectivity: 'Bluetooth 5.0',
      'Water Resistance': 'IPX7',
    },
    stock: 40,
    rating: 4.1,
    num_reviews: 267,
    featured: false,
  },
  {
    name: 'Noise Buds VS104',
    brand: 'Noise',
    category: 'Audio',
    price: 999,
    mrp: 1999,
    description:
      'Noise Buds VS104 true wireless earbuds offer low-latency gaming mode, quad mic ENC, and up to 40 hours of total playback.',
    specifications: {
      Type: 'True Wireless Earbuds',
      'Battery Life': 'Up to 40 hours (with case)',
      Connectivity: 'Bluetooth 5.3',
      'Driver Size': '10mm',
    },
    stock: 55,
    rating: 4.0,
    num_reviews: 421,
    featured: false,
  },

  // ---------------- Accessories ----------------
  {
    name: 'SanDisk Ultra 64GB Pendrive',
    brand: 'SanDisk',
    category: 'Accessories',
    price: 599,
    mrp: 899,
    description:
      'SanDisk Ultra USB 3.0 flash drive offers fast transfer speeds up to 100MB/s in a compact, reliable design.',
    specifications: {
      Capacity: '64GB',
      Interface: 'USB 3.0',
      'Read Speed': 'Up to 100MB/s',
    },
    stock: 100,
    rating: 4.5,
    num_reviews: 890,
    featured: false,
  },
  {
    name: 'SanDisk Extreme 128GB microSD',
    brand: 'SanDisk',
    category: 'Accessories',
    price: 1299,
    mrp: 1899,
    description:
      'SanDisk Extreme microSDXC card delivers high-speed performance for 4K video recording and fast app load times.',
    specifications: {
      Capacity: '128GB',
      Interface: 'UHS-I, A2, V30',
      'Read Speed': 'Up to 190MB/s',
    },
    stock: 70,
    rating: 4.6,
    num_reviews: 456,
    featured: false,
  },
  {
    name: 'Anker PowerCore 10000 Power Bank',
    brand: 'Anker',
    category: 'Accessories',
    price: 1999,
    mrp: 2999,
    description:
      'Anker PowerCore 10000 is one of the smallest and lightest 10000mAh portable chargers, with PowerIQ fast charging.',
    specifications: {
      Capacity: '10000mAh',
      Output: '12W (PowerIQ)',
      Ports: '1x USB-A',
    },
    stock: 45,
    rating: 4.7,
    num_reviews: 678,
    featured: true,
  },
  {
    name: 'Logitech M235 Wireless Mouse',
    brand: 'Logitech',
    category: 'Accessories',
    price: 599,
    mrp: 895,
    description:
      'Logitech M235 wireless mouse offers reliable 2.4GHz connectivity and up to 12 months of battery life in a compact form.',
    specifications: {
      Connectivity: '2.4GHz Wireless',
      'Battery Life': 'Up to 12 months',
      DPI: '1000 DPI',
    },
    stock: 65,
    rating: 4.4,
    num_reviews: 389,
    featured: false,
  },

  // ---------------- Gaming ----------------
  {
    name: 'Logitech G102 Lightsync Gaming Mouse',
    brand: 'Logitech',
    category: 'Gaming',
    price: 1295,
    mrp: 1595,
    description:
      'Logitech G102 Lightsync gaming mouse features customizable RGB lighting and an 8000 DPI optical sensor for precise control.',
    specifications: {
      Sensor: '8000 DPI Optical',
      Connectivity: 'Wired USB',
      Lighting: 'Lightsync RGB',
      Buttons: '6 Programmable',
    },
    stock: 38,
    rating: 4.6,
    num_reviews: 512,
    featured: true,
  },
  {
    name: 'Logitech G213 Prodigy Gaming Keyboard',
    brand: 'Logitech',
    category: 'Gaming',
    price: 3495,
    mrp: 4295,
    description:
      'Logitech G213 Prodigy is a full-size gaming keyboard with vivid RGB lighting and durable spill-resistant keys.',
    specifications: {
      Type: 'Membrane Gaming Keyboard',
      Connectivity: 'Wired USB',
      Lighting: 'RGB Lightsync',
      Layout: 'Full-size',
    },
    stock: 24,
    rating: 4.5,
    num_reviews: 203,
    featured: false,
  },
  {
    name: 'boAt Immortal IM-1000D Gaming Headset',
    brand: 'boAt',
    category: 'Gaming',
    price: 1999,
    mrp: 3990,
    description:
      'boAt Immortal IM-1000D gaming headset delivers immersive 7.1 channel audio with an adjustable mic and RGB lighting.',
    specifications: {
      Type: 'Wired Gaming Headset',
      Sound: '7.1 Virtual Surround',
      Connectivity: 'USB',
      Microphone: 'Adjustable Noise-Cancelling',
    },
    stock: 30,
    rating: 4.3,
    num_reviews: 156,
    featured: false,
  },

  // ---------------- Wearables ----------------
  {
    name: 'Noise ColorFit Pulse 2 Smartwatch',
    brand: 'Noise',
    category: 'Wearables',
    price: 1699,
    mrp: 3999,
    description:
      'Noise ColorFit Pulse 2 smartwatch features a 1.69-inch HD display, SpO2 monitoring, and up to 7 days of battery life.',
    specifications: {
      Display: '1.69-inch HD',
      'Battery Life': 'Up to 7 days',
      'Water Resistance': 'IP68',
      Sensors: 'Heart Rate, SpO2',
    },
    stock: 48,
    rating: 4.1,
    num_reviews: 634,
    featured: true,
  },
  {
    name: 'boAt Wave Call Smartwatch',
    brand: 'boAt',
    category: 'Wearables',
    price: 1299,
    mrp: 2990,
    description:
      'boAt Wave Call smartwatch supports Bluetooth calling, 700+ nits brightness, and a week-long battery life.',
    specifications: {
      Display: '1.69-inch HD, 700 nits',
      'Battery Life': 'Up to 7 days',
      'Water Resistance': 'IP68',
      Connectivity: 'Bluetooth Calling',
    },
    stock: 52,
    rating: 4.0,
    num_reviews: 487,
    featured: false,
  },
  {
    name: 'Samsung Galaxy Watch 6',
    brand: 'Samsung',
    category: 'Wearables',
    price: 24999,
    mrp: 29999,
    description:
      'Samsung Galaxy Watch 6 offers advanced health tracking, a bright sapphire crystal display, and seamless Galaxy ecosystem integration.',
    specifications: {
      Display: '1.5-inch Super AMOLED',
      'Battery Life': 'Up to 40 hours',
      'Water Resistance': '5ATM + IP68',
      Sensors: 'ECG, BIA, Heart Rate',
    },
    stock: 16,
    rating: 4.7,
    num_reviews: 78,
    featured: true,
  },
];

// Attach two placeholder images per product, keyed off the product name.
const seedProducts = products.map((p) => ({
  ...p,
  images: [productImage(p.name, '2563eb'), productImage(p.brand, '1e293b')],
}));

module.exports = seedProducts;
